spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/course_service
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret-key: eqS5fqwmlhALPxmsrbNZOX8/INdAm9RQcaT9brFuk3VOMRrj1ITddcm+QwSWVLhP4arkHnya6naMKSNVUiPJb0p+0SjhkKKmXPTuJtsL96w=